group = io.github.sgrishchenko
version = 1.0.0-alpha.107

org.gradle.jvmargs = -Xms2g -Xmx4g
org.gradle.configuration-cache = true
org.gradle.parallel = true
org.gradle.caching = true

kotlin.js.yarn = false
kotlin.js.stdlib.dom.api.included = false

kotlinVersion = 2.3.20
kotlinCoroutinesVersion = 1.10.2
mavenPublishVersion = 0.36.0
gradlePublishVersion = 2.1.1
seskarVersion = 4.40.0

ktlintVersion = 1.8.0

wrappersVersion = 2026.4.7
arrowKtVersion = 2.2.0
nodeVersion = 24.12.0
typescriptVersion = ^6.0.2
mochaVersion = 12.0.0-beta-10
tsJsonSchemaGeneratorVersion = ^2.9.0
