// Generated by Karakum - do not modify it manually!

@file:JsModule("js-file-download")
@file:Suppress(
    "NON_EXTERNAL_DECLARATION_IN_INAPPROPRIATE_FILE",
)

package js.file.download

import js.buffer.ArrayBuffer
import js.buffer.ArrayBufferView
import web.blob.Blob

external fun fileDownload(
    data: String,
    filename: String,
    mime: String = definedExternally,
    bom: String = definedExternally,
): Unit

external fun fileDownload(
    data: ArrayBuffer,
    filename: String,
    mime: String = definedExternally,
    bom: String = definedExternally,
): Unit

external fun fileDownload(
    data: ArrayBufferView<*>,
    filename: String,
    mime: String = definedExternally,
    bom: String = definedExternally,
): Unit

external fun fileDownload(
    data: Blob,
    filename: String,
    mime: String = definedExternally,
    bom: String = definedExternally,
): Unit
